### ISSUE TITLE
Magic byte error

### ISSUE THREAD

**Issue by yonigoyhman** [SOHU-Co/kafka-node#1208]
Hey,
I am using the ConsumerGroup to consume messages.
After several messages (2 - 50) I suddenly get the following error:

`Error: Not a message set. Magic byte is 2` 

The messages are produced using a different client producer. 
Messages are In binary format, (I've set the Client format accordingly)
Kafka version is: 2.1.0

Thanks.

**Comment by hyperlink** [comment]
I noticed this happens when the `fetchMaxBytes` is set too low the broker will start sending fetch responses in RecordBatch format instead of MessageSet.

**Comment by yonigoyhman** [comment]
Thanks @hyperlink , looks like this solves the issue.

I would expect a more explanatory message for this type of error though :)

**Comment by Sudheer312** [comment]
> I noticed this happens when the `fetchMaxBytes` is set too low the broker will start sending fetch responses in RecordBatch format instead of MessageSet.

@hyperlink what is the minimum number that we can set ? I have to consume the messages slowly.

**Comment by Albinzr** [comment]
If so what is the min value that we can set for '**fetchMaxBytes**'

**Comment by IharKrasnik** [comment]
Is there some specific configuration option for Kafka broker in order to fix this error and allow kafka-node working with low fetchMaxBytes value?

**Comment by Albinzr** [comment]
@IharKrasnik you have to edit some items in server.properties files

**Comment by IharKrasnik** [comment]
I wonder which configuration option we can change exactly if there is any indeed.

**Comment by Albinzr** [comment]
server.properity -> socket.request.max.bytes=104857600

**Comment by xino1010** [comment]
In docker-compose.yml

```
image: wurstmeister/kafka
environment:
   KAFKA_MESSAGE_MAX_BYTES: 200000000
   KAFKA_MAX_PARTITION_FETCH_BYTES: 200000000
   KAFKA_FETCH_MAX_BYTES: 200000000
   KAFKA_MAX_REQUEST_SIZE: 200000000
   KAFKA_SOCKET_REQUEST_MAX_BYTES: 200000000
```
in node.js:

```
consumer = new Consumer(
      kafkaClient,
      [
        {
          topic: 'my-topic',
        },
      ],
      {
        fetchMaxBytes: 200000000,
      },
    );
```
