### ISSUE TITLE
Broker not available (loadMetadataForTopics)

### ISSUE THREAD

**Issue by mugwump** [SOHU-Co/kafka-node#1386]
I'm trying to connect from one docker-container running node to another container running Kafka, and I can't seem to get through to send a message. Here is what I do to set up the producer:

```
var kafka = require('kafka-node'),
      Producer = kafka.Producer;

client = new kafka.KafkaClient({kafkaHost:"kafka:9092"});
var producer = new Producer(client);
producer.send([{topic: "test", messages:["test1","test2"]}], (err,rslt) => console.log(err, rslt));
```
always throws a 
```
> BrokerNotAvailableError: Broker not available (loadMetadataForTopics)
    at new BrokerNotAvailableError (/home/node/app/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.loadMetadataForTopics (/home/node/app/node_modules/kafka-node/lib/kafkaClient.js:891:21)
    at RetryOperation._fn (/home/node/app/node_modules/kafka-node/lib/baseClient.js:360:12)
    at Timeout._onTimeout (/home/node/app/node_modules/kafka-node/node_modules/retry/lib/retry_operation.js:68:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  message: 'Broker not available (loadMetadataForTopics)'
}
```

and the producer never gets ready, so 
```
producer.on("ready", () => console.log("producer is ready now"));
```
is never called.

Kafka itself is set-up with the following docker-compose.yml: 

```
**kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOSTNAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100**
``` 

so it should be available at kafka:9092. Publishing messages using the command-line-producer works from within the kafka-node, so kafka itself appears to be working. 

Does anyone have an idea what else is going wrong here? Thx for any help!

**Comment by mugwump** [comment]
So I switched on the logging, I currently have no idea how to interpret this properly: Does the initial message:

```
payloads has no leaders! Our metadata could be out of date try refreshingMetadata [
  {
    topic: 'test',
    partition: 0,
    messages: [ [Object], [Object] ],
    attributes: 0
  }
]
refresh metadata currentAttempt 1
missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
```
mean on some level I can connect, but susequent calls fail?!

These calls are then followed by a lot of:
```
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
```
which probably means that at this point, Kafka does not reply any more. So my gues is, that there is something wrong here with the network-setup, and while the error-messages are maybe a bit vague, kafka-node does not seem to be the problem...

But I still have attached the whole error-log, maybe someone still has an idea on how to fix this...



```
Connect attempt 1
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Sending messages...
{
  kafkaHost: 'kafka:9092',
  connectTimeout: 10000,
  requestTimeout: 30000,
  idleConnection: 300000,
  reconnectOnIdle: true,
  autoConnect: true,
  versions: { disabled: false, requestTimeout: 500 },
  connectRetryOptions: {
    retries: 5,
    factor: 2,
    minTimeout: 1000,
    maxTimeout: 60000,
    randomize: true
  },
  maxAsyncRequests: 10,
  noAckBatchOptions: null
}
compressing messages if needed
payloads has no leaders! Our metadata could be out of date try refreshingMetadata [
  {
    topic: 'test',
    partition: 0,
    messages: [ [Object], [Object] ],
    attributes: 0
  }
]
refresh metadata currentAttempt 1
missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
waitUntilReady [BrokerWrapper kafka:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)]
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
kafka-node-client socket closed kafka:9092 (hadError: true)
Connect attempt 2
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
kafka-node-client socket closed kafka:9092 (hadError: true)
Connect attempt 3
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
kafka-node-client socket closed kafka:9092 (hadError: true)
Connect attempt 4
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
kafka-node-client socket closed kafka:9092 (hadError: true)
Connect attempt 5
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
kafka-node-client socket closed kafka:9092 (hadError: true)
refresh metadata currentAttempt 2
refresh metadata currentAttempt 3
refresh metadata currentAttempt 4
refresh metadata currentAttempt 5
refresh metadata currentAttempt 6
refresh metadata currentAttempt 7
refresh metadata currentAttempt 8
refresh metadata currentAttempt 9
refresh metadata currentAttempt 10
refresh metadata currentAttempt 11
refresh metadata error Broker not available (loadMetadataForTopics)
BrokerNotAvailableError: Broker not available (loadMetadataForTopics)
    at new BrokerNotAvailableError (/home/node/app/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.loadMetadataForTopics (/home/node/app/node_modules/kafka-node/lib/kafkaClient.js:891:21)
    at RetryOperation._fn (/home/node/app/node_modules/kafka-node/lib/baseClient.js:360:12)
    at Timeout._onTimeout (/home/node/app/node_modules/kafka-node/node_modules/retry/lib/retry_operation.js:68:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  message: 'Broker not available (loadMetadataForTopics)'
} undefined
Connect attempt 6
Trying to connect to host: kafka port: 9092
kafka-node-client createBroker kafka:9092
Socket Error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
failed to connect because of  Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
exhausted retries. Main error Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN kafka
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on Producer instance at:
    at KafkaClient.<anonymous> (/home/node/app/node_modules/kafka-node/lib/baseProducer.js:101:10)
    at KafkaClient.emit (events.js:210:5)
    at /home/node/app/node_modules/kafka-node/lib/kafkaClient.js:165:16
    at /home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:3888:9
    at /home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:988:17)
    at /home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:969:16
    at /home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:3885:13
    at /home/node/app/node_modules/kafka-node/lib/kafkaClient.js:207:9
    at /home/node/app/node_modules/kafka-node/node_modules/async/dist/async.js:969:16 {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'kafka'
}
```

**Comment by mugwump** [comment]
oops: So the reason for this was a misconfiguration in the accessing container: For some reasons it used ``network_mode: host`` and therefore could not resolve the name of the kafka-container, fixed it, now the calls got through.

sry for the confusion, was totally un-related to kafka-node.

**Comment by jaiswarvipin** [comment]
**My docker-compose file**
```
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_LISTENERS: INTERNAL://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
```

**and Producer code is**


```
var kafka = require('kafka-node'),
    Producer = kafka.Producer,
	KeyedMessage = kafka.KeyedMessage,
    client = new kafka.KafkaClient({kafkaHost:"localhost:9094"}),

    producer = new Producer(client),
    km = new KeyedMessage('key', 'message'),
    payloads = [
        { topic: 'topic1', messages: 'hi', partition: 0 },
        { topic: 'topic1', messages: ['hello', 'world', km] }
    ];

client.createTopics(topicsToCreate, (error, result) => {
				
				echo ("------------------------KAFAK--------------------")
				console.log(error);
				console.log(result);			
			});
```


Getting below error, while creating the topic before sending pay-load to topics

```
{ BrokerNotAvailableError: Broker not available (loadMetadataForTopics)
    at new BrokerNotAvailableError (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\errors\BrokerNotAvailableError.js:11:9)
    at KafkaClient.loadMetadataForTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:891:21)
    at KafkaClient.loadMetadata (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:876:8)
    at KafkaClient.getController (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:267:8)
    at KafkaClient.sendControllerRequest (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:1219:8)
    at KafkaClient.createTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:935:8)
    at C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\index_behind_kong.js:60:11
    at C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\baseClient.js:370:18
    at KafkaClient.loadMetadataForTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:891:12)
    at RetryOperation._fn (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\baseClient.js:360:12) message: 'Broker not available (loadMetadataForTopics)' }
undefined
```

I have gave the delay of 5 seconds before calling to **createtopic** method, however no luck found.

Kindly assist.

**Comment by jaiswarvipin** [comment]
Finally got the solution. I was doing on mistake. By default Apache Kafka create the 3 replication, this mean its by default create 3 broker as well. However aboe YAML create only one broker, and looknig for other 2 which is not created. hence we are getting the same error.

Fix

```
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
```

then `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1` tell the Apache kafka that we Wanted to create only one replication and its work 

Happy coding :)

Thanks & Regards
Jaiswar Vipin Kumar R.
