### ISSUE TITLE
BrokerNotAvailableError: Broker not available

### ISSUE THREAD

**Issue by MayhemYDG** [SOHU-Co/kafka-node#160]
Reduced test case:

1. Launch the following code.
2. Wait a moment to let the client connect to kafka.
3. ^C
4. Program crashes.

```js
var kafka    = require('kafka-node');
var client   = new kafka.Client('localhost:2181');
var consumer = new kafka.Consumer(client, []);
consumer.addTopics(['admin'], function(err) {
  if (err) console.error(log);
});
process.once('SIGINT', function() {
  consumer.close();
});
```

```
$ iojs test.js 
^C
events.js:125
      throw er; // Unhandled 'error' event
            ^
BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/vagrant/test/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:11)
    at Socket.<anonymous> (/vagrant/test/node_modules/kafka-node/lib/client.js:501:43)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)
```

This only happens with `kafka-node@0.2.19`, `kafka-node@0.2.18` exits gracefully.
It also happens with `client.close()` instead of `consumer.close()`.

**Comment by estliberitas** [comment]
@haio somehow callback queue is not cleared in this case

**Comment by haio** [comment]
@estliberitas when the broker is in longpolling mode it should not emit error. And each socket connection should has its own callback queue, I will make the fix.

**Comment by estliberitas** [comment]
Well it already has own callback queue, I implemented it. :-) All you need
is check for `longpolling` in `close` event listener for socket. :-)

**Comment by haio** [comment]
The current implemention is group the callbacks by `host:port`, if we have 2 socket connecting 0.0.0.0:9093, one of them is longpolling, when one socket get end event, it will clear callbacks in `0.0.0.0:9093`, thus accidentally clear aonther socket's callback queue.

**Comment by MayhemYDG** [comment]
It seems to be working fine in `kafka-node@0.2.20` now, thanks!

**Comment by jaiswarvipin** [comment]
**My docker-compose file**
```
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_LISTENERS: INTERNAL://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
```

**and Producer code is**


```
var kafka = require('kafka-node'),
    Producer = kafka.Producer,
	KeyedMessage = kafka.KeyedMessage,
    client = new kafka.KafkaClient({kafkaHost:"localhost:9094"}),

    producer = new Producer(client),
    km = new KeyedMessage('key', 'message'),
    payloads = [
        { topic: 'topic1', messages: 'hi', partition: 0 },
        { topic: 'topic1', messages: ['hello', 'world', km] }
    ];

client.createTopics(topicsToCreate, (error, result) => {
				
				echo ("------------------------KAFAK--------------------")
				console.log(error);
				console.log(result);			
			});
```


Getting below error, while creating the topic before sending pay-load to topics

```
{ BrokerNotAvailableError: Broker not available (loadMetadataForTopics)
    at new BrokerNotAvailableError (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\errors\BrokerNotAvailableError.js:11:9)
    at KafkaClient.loadMetadataForTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:891:21)
    at KafkaClient.loadMetadata (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:876:8)
    at KafkaClient.getController (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:267:8)
    at KafkaClient.sendControllerRequest (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:1219:8)
    at KafkaClient.createTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:935:8)
    at C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\index_behind_kong.js:60:11
    at C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\baseClient.js:370:18
    at KafkaClient.loadMetadataForTopics (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\kafkaClient.js:891:12)
    at RetryOperation._fn (C:\wamp64\www\ws-proxy\HOZ-KOG-WebSocket_NodeJS\node_modules\kafka-node\lib\baseClient.js:360:12) message: 'Broker not available (loadMetadataForTopics)' }
undefined
```

I have gave the delay of 5 seconds before calling to **createtopic** method, however no luck found.

Kindly assist.

**Comment by jaiswarvipin** [comment]
Finally got the solution. I was doing on mistake. By default Apache Kafka create the 3 replication, this mean its by default create 3 broker as well. However aboe YAML create only one broker, and looknig for other 2 which is not created. hence we are getting the same error.

Fix

```
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
```

then `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1` tell the Apache kafka that we Wanted to create only one replication and its work 

Happy coding :)

Thanks & Regards
Jaiswar Vipin Kumar R.
