### ISSUE TITLE
Consumers do not recover from network issues with Kafka server

### ISSUE THREAD

**Issue by hyperlink** [SOHU-Co/kafka-node#277]
We have observed behavior inside our application where consumers do not receive `message` events after a temporary network interruption to the Kafka server. We expect to receive `message` events after the network issue has been resolved but unfortunately this is not the case.

### Test Summary

We have a dockerized kafka server and a zookeeper server. We expose ports to these services. Our application is running locally. Using `iptables` we block the IP address to the Kafka server and observe how the application behaves.

### Test files

Add below test files to `kafka-node`

`./docker-compose.yml`

```yml
zookeeper:
  image: hyperlink/zookeeper
  privileged: true
  ports:
    - "2181:2181"
kafka:
  image: mdlavin/kafka:0.8.1.1-1-topic-creation
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME:
    KAFKA_CREATE_TOPICS: "KafkaConnectivityTest"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
```

`./kafkatest.js`

```javascript
#!/usr/bin/env node

var kafka  = require('./kafka')
var topics = [ { topic: 'KafkaConnectivityTest' } ]
var client = new kafka.Client('192.168.99.100:2181', 'kafka-testing')

var consumer = new kafka.HighLevelConsumer(client, topics, {groupId: 'kafka.tester'})

consumer.on('error', function(error){
	console.error('an error happened', error)
})

consumer.on('message', function(message){
	console.log('received message', message)
})
```

Bash script to start docker containers

`./start.sh`

```
DOCKER_VM_IP=`docker-machine ip dev`

if [ "$?" != "0" ]; then
    DOCKER_VM_IP=''
fi

if [ "$DOCKER_VM_IP" != "" ]; then
    echo "Docker VM is running."
    echo "Docker VM IP Address: $DOCKER_VM_IP"
else
    echo "Docker VM is not running."
    docker-machine start dev
fi

export KAFKA_ADVERTISED_HOST_NAME=$(docker-machine ip dev 2> /dev/null)

eval "$(docker-machine env dev)"
docker-compose up
```
	
#### Install docker and docker-machine docker-compose and create machine

	brew install docker docker-machine docker-compose
	docker-machine create --driver virtualbox dev
	./start.sh

### Steps to reproduce

* Start the kafka console producer to send messages
`./bin/kafka-console-producer.sh --broker-list 192.168.99.100:9092 --topic KafkaConnectivityTest`
* Run `./kafkatest.js`
* Send a test message through the producer console and verify a message show up
* Shell to the docker kafka container `docker exec -it kafkanode_kafka_1 bash`
* In the container execute `iptables -A INPUT -s "192.168.99.1" -j REJECT; iptables -A OUTPUT -s "192.168.99.1" -j REJECT;`
* Verify the record is in iptables `iptables -nvL`
* Verify from your machine that port is no longer open `nmap -p 9092 192.168.99.100`
* Wait at least 1 minute. You should expect see error messages soon.

The errors are initially

	an error happened { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }

Then followed by many of

	an error happened { [Error: connect ECONNREFUSED 192.168.99.100:9092]` as the socket tries to reconnect.
	
* Once the messages show up remove the rule by executing `iptables -D INPUT -s "192.168.99.1" -j REJECT; iptables -D OUTPUT -s "192.168.99.1" -j REJECT;` in the kafka container
* Verify from your machine the port is available again `nmap -p 9092 192.168.99.100`
* Send another test message through the producer console. We expect the message to show up but it does not.

I have a PR fix incoming for this issue.
